#!/usr/bin/env bash
#check the number of argument passed to a terminal
#if argument is less than 3 Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
#if the argument is greater than 4 print it

if [ "$#" -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
