#!/usr/bin/env bash
#a script that display a list of currently running processes
#must show all process, for all users, including those which might not have a TTY
#Display in a user oriented format
#Show process heirachy

ps -uHt
