#!/usr/bin/env bash
#a list of currently running process
#must show all process, for all users, including those which might not have a TTY
#Display in a user-oriented format
#show process hierarchy
ps aux
