#!/usr/bin/env bash
#a bash script that displays to infinity and beyond
#a sleep 2 in between each iteration
#i am invicible!!! when receiving a SIGTERM signal

trap "echo I am invincible!!!; exit" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
