#!/usr/bin/env bash
# The script is displaying 'best school ten times with an exception when it reaches number 9

i=0
while [ $i -lt 10 ]
do
echo "Best School"
if [ "$i" = 8 ];
then
echo "Hi"
fi
((i++))

done
