#!/usr/bin/env bash
# This script priint bad luck for the fourth iteration and for the 8th iteration it prints good luck

i=0
while [ $i -lt 10 ];
do
if [ "$i" = 3 ];
then
echo "bad luck"
elif [ "$i" = 7 ];
then
echo "good luck"
else
echo "Best School"
fi
((i++))
done
