#!/usr/bin/env bash
#This script shows the number that represent bad luck from different countries

i=1
while [ $i -lt 21 ];
do
echo $i
case $i in
4)
echo "bad luck from china"
;;
9)
echo "bad luck from japan"
;;
17)
echo "bad luck from Italy"
;;
esac
((i++))
done
