#!/usr/bin/env bash
#a bash script that configures an ubuntu server with the below requirements
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

sudo cp /etc/hosts ~/hosts.new
sed -i 's/^172.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
